export const ActionTypes = {
    NUMBER_CART: 'NUMBER_CART',
    ADD_TO_CART: 'ADD_TO_CART',
    REMOVE_FROM_CART: 'REMOVE_FROM_CART',
    INCREASE_QUANTITY: 'INCREASE_QUANTITY',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    EMPTY_CART: 'EMPTY_CART',
    ADD_TO_FAVOURITE: 'ADD_TO_FAVOURITE',
    REMOVE_FROM_FAVOURITE: 'REMOVE_FROM_FAVOURITE',
}